# Site settings
title: Amelia Meyer
description: My data science portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://ameliameyer.github.io/home" # the base hostname & protocol for your site 
# User settings
username: Amelia Meyer
user_description: I graduated in June of 2022 with a B.S. in Statistics and Data Science, and a Minor in German.  
user_title: Data Science & Machine Learning 
email: amelianmeyer@gmail.com 
twitter_username: ameliameyer
github_username: ameliameyer
gplus_username:  ameliameyer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
